### ISSUE TITLE
Haxe version

### ISSUE THREAD

**Issue by nanjizal** [johnnovak/raytriangle-test#2]
I can create a pull request if suitable, but your format does not really fit the hxml files which are not needed but useful.
https://github.com/nanjizal/rayTriangle-test

Haxe JS/c++ seems fairly reasonable performance the others are not good, not tried HashLink, PHP or Lua, unsure if the code is correct if you get a chance take a quite look.  But would be curious about comparative results against your machine tests. 
 
Notice **-D avoid_typedef** this compile switches to use a Class for Vec3 rather than a typedef. Surprisingly class seems faster on javascript.

Perhaps less inlining would help? and I have not looked into macro use only abstracts.

**Comment by johnnovak** [comment]
Later reply, but sure, create a Haxe version if you like.

**Comment by nanjizal** [comment]
the Haxe js results see console
https://nanjizal.github.io/rayTriangle-test/index.html
