### ISSUE TITLE
Comparison with frameworks (Java3D, numpy + pyrr etc.)

### ISSUE THREAD

**Issue by hhackbarth** [johnnovak/raytriangle-test#5]
Thanks for your interesting comparison. As you usually would use optimized framework libraries like numpy and pyrr in Python with that kind of 3D / multidimensional objects, it would also be intresting to see, how it can catchup with them.

Also for Java it would be interesting to see, if and how it speeds up when using Java3D instead of your own plain Vec3D implementation. Möller-Trumbore using Java 3D is given here: https://en.wikipedia.org/wiki/M%C3%B6ller%E2%80%93Trumbore_intersection_algorithm.

**Comment by johnnovak** [comment]
PRs welcome :)
